### ISSUE TITLE
Event Heading/Banner on website - Access to change

### ISSUE THREAD

**Issue by CiaraOSPO** [ospoplusplus/ospoplusplus#60]
Hi there Diren

I tried to update our event banner on the website this week (as you showed me) but I don't seem to have access to update it.  Can you grant me permission to change it in the future?

Thanks a million

Ciara

**Comment by direnakkoc** [comment]
Hi @CiaraOSPO,
Are you sure? Because we all have the same access to the repo.
Could you share the error message with me please?
![](https://files.slack.com/files-pri/T012VH4PWF5-F04P5TE7125/screenshot_2023-02-09_at_07.57.25.png)

**Comment by CiaraOSPO** [comment]
Access added! 

Thanks for the new permissions @RichardLitt
