### ISSUE TITLE
Moving events from 'Future events' on the website to 'Past Events'

### ISSUE THREAD

**Issue by CiaraOSPO** [ospoplusplus/ospoplusplus#61]
Hi Diren

Re:  https://ospoplusplus.org/events/

I think you mentioned in a recent call that you had an automated function for 'future events' moving to the 'past events' section once the event had run.  I've noticed that this didn't happen this week.

Let me know if I've misunderstood this and need to create an issue each time and OSPO++ is over.

Thanks very much, 

Ciara

**Comment by direnakkoc** [comment]
Hi @CiaraOSPO,
Yes, it is automated however where there is no change on the website GitHub actions don't refresh themselves.
You don't need to change any code for that you can either make a small change for any other section to trigger GitHub Actions or you can manually trigger the GitHub actions on the console.
I've just triggered Github Actions. It will refresh the website page. If that is not clear happy to explain it further.
