### ISSUE TITLE
Change event banner/heading on website

### ISSUE THREAD

**Issue by CiaraOSPO** [ospoplusplus/ospoplusplus#63]
Hi @direnakkoc 

We need to change the current event banner on the website to the following text: 

Register now for our next Community Call: OSS Licensing at Universities - 12pm EST, Thursday February 23rd

This text should contain a link to: https://www.eventbrite.com/e/oss-licensing-in-universities-tickets-539748611627

Thanks a million (and we'll talk about what happened when I tried to update it last week).

Ciara

**Comment by direnakkoc** [comment]
Hi @CiaraOSPO, 
Sure let's talk about what issue happened when you tried.

**Comment by CiaraOSPO** [comment]
Thanks @direnakkoc
